spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #
            client-secret: #
          facebook:
            client-id: #
            client-secret: #


#add my authorization server