server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 583133030463-7855bnfbit2odl4v0a40plkghinpkf6b.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 1545569249284628
            client-secret: e40b66ac8a3086c31363fae729265926
      #my auth server that supports JWT header
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8000
          #todo
#          spotify:
#            client-id: f4d6bf91134649969051be9a6b8f40ac
#            client-secret: 90d8d7b5d6284cdd8a2dd666235346d8