server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 583133030463-7855bnfbit2odl4v0a40plkghinpkf6b.apps.googleusercontent.com
            client-secret: #
          facebook:
            client-id: 1545569249284628
            client-secret: #
      #my auth server that supports JWT header
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8000
          #todo
#          spotify:
#            client-id: f4d6bf91134649969051be9a6b8f40ac
#            client-secret: dddb822569264307b88a58af8c4468e1